---
    - name: dockerapp
      hosts: appserver
      become: true
      vars_files:
        - credentials.yml
      tasks:
        - name: 1. Install python-docker
          apt:
            name: python-docker
            update_cache: yes
            state: present

        - name: 2. Install python
          raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
          changed_when: false
    
        - name: 3. DockerHub login
          docker_login:
            username: "{{ item.key }}"
            password: "{{ item.value.password }}"
          with_dict: "{{ credentials.users }}"
    
        - name: 3. Run container with app
          docker_container:
            name: mycontainer
            state: started
            image: volkmydj/otus-reddit:1.0
            ports: "9292:9292"