global:
    slack_api_url: 'https://hooks.slack.com/services/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'
  
  route:
    receiver: 'slack-notifications'
  
  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#ilya_semernya'
