version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - back_net

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: es01
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - front_net
      - back_net

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - front_net
      - back_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

networks:
  back_net:
  front_net:
